# Generated by Django 6.0.4 on 2026-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_gender_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('basic', 'Базовая коллекция'), ('evening', 'Вечерняя коллекция'), ('sport', 'Спортивная коллекция'), ('business', 'Деловая коллекция'), ('casual', 'Повседневная коллекция'), ('city', 'Капсула "Город"'), ('relax', 'Капсула "Отдых"'), ('limited', 'Limited Edition')], max_length=50, null=True, verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('spring-summer-2026', 'Весна-Лето 2026'), ('autumn-winter-2026', 'Осень-Зима 2026'), ('cruise', 'Круизная коллекция'), ('preorder', 'Предзаказ')], max_length=50, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('minimalism', 'Минимализм'), ('casual_style', 'Кэжуал'), ('classic', 'Классика'), ('sport-chic', 'Спорт-шик'), ('romantic', 'Романтика'), ('boho', 'Бохо')], max_length=50, null=True, verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('dresses', 'Платья'), ('blouses', 'Блузы и рубашки'), ('jeans_women', 'Джинсы'), ('trousers_women', 'Брюки'), ('skirts', 'Юбки'), ('jackets_women', 'Жакеты и пиджаки'), ('knitwear', 'Трикотаж'), ('outerwear_women', 'Верхняя одежда'), ('shirts', 'Рубашки'), ('tshirts', 'Футболки'), ('jeans_men', 'Джинсы'), ('trousers_men', 'Брюки'), ('hoodies', 'Худи и свитшоты'), ('jackets_men', 'Куртки'), ('suits', 'Костюмы'), ('outerwear_men', 'Верхняя одежда'), ('bags', 'Сумки'), ('belts', 'Ремни'), ('hats', 'Головные уборы'), ('scarves', 'Шарфы и платки'), ('gloves', 'Перчатки'), ('jewelry', 'Украшения'), ('glasses', 'Очки'), ('sneakers', 'Кроссовки'), ('heels', 'Туфли'), ('boots', 'Ботинки'), ('winter_boots', 'Сапоги'), ('flats', 'Балетки'), ('loafers', 'Лоферы'), ('sandals', 'Сандалии')], max_length=50, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доступные размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='URL-идентификатор'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='shop_produc_subcate_942dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection'], name='shop_produc_collect_a55238_idx'),
        ),
    ]
