# Generated by Django 6.0.4 on 2026-05-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderitem_product_name_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Женское'), ('men', 'Мужское'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender'], name='shop_produc_gender_04eeb6_idx'),
        ),
    ]
