# Generated by Django 5.0.3 on 2026-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото (URL)'),
        ),
    ]
