# Generated by Django 5.0.3 on 2026-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото 3'),
        ),
    ]
