# Generated by Django 5.0.3 on 2026-05-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image_alter_product_image_url'),
    ]

    operations = [
    ]
