# Generated by Django 5.0.3 on 2026-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_create_admin_user'),
    ]

    operations = [
    ]
